apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    run: test-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    run: test-server