- hosts: all
  become: yes
  tasks:
    - name: Run the equivalent of "apt-get update && apt-get upgrade"
      register: result
      until: result is succeeded
      retries: 10
      delay: 5
      apt:
        update_cache: yes
        upgrade: yes

